# Generated by Django 2.0.6 on 2018-06-18 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ('course_name',),
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=256)),
                ('year', models.SmallIntegerField(default=0)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('group_name',),
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='groups',
            field=models.ManyToManyField(to='courseware.Groups'),
        ),
    ]
