# Generated by Django 2.0.6 on 2018-06-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0002_courses_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingElementBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.CreateModel(
            name='HtmlTE',
            fields=[
                ('teachingelementbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courseware.TeachingElementBase')),
                ('html', models.TextField()),
            ],
            bases=('courseware.teachingelementbase',),
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('teachingelementbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courseware.TeachingElementBase')),
                ('question', models.CharField(max_length=255)),
            ],
            bases=('courseware.teachingelementbase',),
        ),
        migrations.AddField(
            model_name='courses',
            name='elements',
            field=models.ManyToManyField(to='courseware.TeachingElementBase'),
        ),
    ]
