# Generated by Django 2.0.6 on 2018-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0003_auto_20180628_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='elements',
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teachingelementbase',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='chapters',
            name='elements',
            field=models.ManyToManyField(to='courseware.TeachingElementBase'),
        ),
        migrations.AddField(
            model_name='courses',
            name='chapters',
            field=models.ManyToManyField(to='courseware.Chapters'),
        ),
    ]
