# Generated by Django 2.0.6 on 2018-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0004_auto_20180628_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlte',
            name='type',
            field=models.CharField(default='HTML', max_length=20),
        ),
        migrations.AddField(
            model_name='reflection',
            name='type',
            field=models.CharField(default='Reflection', max_length=20),
        ),
    ]
