# Generated by Django 2.0.6 on 2018-07-03 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0005_auto_20180628_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='chapters',
        ),
        migrations.AddField(
            model_name='chapters',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courseware.Courses'),
        ),
        migrations.AddField(
            model_name='teachingelementbase',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courseware.Chapters'),
        ),
        migrations.AddField(
            model_name='teachingelementbase',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courseware.Courses'),
        ),
    ]
