# Generated by Django 2.0.6 on 2018-07-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0007_auto_20180703_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='course',
        ),
        migrations.AddField(
            model_name='courses',
            name='chapters',
            field=models.ManyToManyField(to='courseware.Chapters'),
        ),
        migrations.AlterField(
            model_name='teachingelementbase',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseware.Courses'),
        ),
    ]
