# Generated by Django 2.0.6 on 2018-07-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0008_auto_20180717_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='chapters',
        ),
        migrations.AddField(
            model_name='chapters',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chapters',
            name='parent_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courseware.Courses'),
        ),
    ]
