# Generated by Django 2.0.6 on 2018-07-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0011_remove_teachingelementbase_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlte',
            name='type',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='type',
        ),
        migrations.AddField(
            model_name='teachingelementbase',
            name='te_type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('Reflection', 'Reflection')], default='HTML', max_length=2),
        ),
    ]
