# Generated by Django 2.0.6 on 2018-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0012_auto_20180719_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingelementbase',
            name='te_type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('Reflection', 'Reflection')], default='HTML', max_length=20),
        ),
    ]
